// 基础控件 【左面板】
export const basicComponents = [
  {
    icon: 'icon-ym icon-ym-generator-todo',
    label: '我的待办',
    ccitKey: 'todo',
    title: '我的待办',
    showTitle: true,
    showBlock: true,
    showIcon: true,
    blockColor: '#506CD2',
    blockWidth: 5,
    usePortalStyle: true,
    showMore: true,
    moreType: 'sys',
    moreUrl: '/workFlow/flowTodo',
    moreParams: {},
    showFresh: true,
    radius: 8,
    themeColor: '',
    titleBorder: '1px solid #EBEEF5',
    titleCss: '',
    opacity: 1,
    draggable: true,
    resizable: true,
    editable: true,
    lock: false,
    w: 12,
    h: 4,
    minW: 1,
    minH: 1,
    maxW: 24,
    maxH: 12,
  },
  // {
  //   icon: 'icon-ym icon-ym-generator-todolist',
  //   label: '待办事项',
  //   ccitKey: 'todoList',
  //   title: '待办事项',
  //   showTitle: true,
  //   showBlock: true,
  //   showIcon: true,
  //   blockColor: '#506CD2',
  //   blockWidth: 5,
  //   usePortalStyle: true,
  //   showMore: true,
  //   moreType: 'sys',
  //   moreUrl: '/workFlow/flowTodo',
  //   moreParams: {},
  //   showFresh: true,
  //   radius: 8,
  //   themeColor: '',
  //   titleBorder: '1px solid #EBEEF5',
  //   titleCss: '',
  //   opacity: 1,
  //   draggable: true,
  //   resizable: true,
  //   editable: true,
  //   lock: false,
  //   w: 12,
  //   h: 7,
  //   minW: 1,
  //   minH: 1,
  //   maxW: 24,
  //   maxH: 12,
  //   showPagination: false,
  //   innerTabs: [
  //     {
  //       label: '待办', name: 'sys', show: true
  //     },
  //     { label: '已办', name: 'complate', show: true }
  //   ],
  //   pageSize: 5,
  //   list: [
  //     { label: '待办标题', prop: 'taskName', selection: true },
  //     { label: '待办编号', prop: 'sysTaskId', selection: true },
  //     { label: '推送时间', prop: 'sendTime', selection: true },
  //     { label: '当前处理用户', prop: 'handleUserName', selection: true },
  //     { label: '上一环节用户', prop: 'sendUserName', selection: true },
  //     { label: '待办名称', prop: 'typeName', selection: true },
  //     { label: '活动名称', prop: 'linkName', selection: true }
  //   ],
  // },
  {
    icon: 'icon-ym icon-ym-generator-function',
    label: '常用功能',
    ccitKey: 'commonFunc',
    title: '常用功能',
    showTitle: true,
    showBlock: true,
    showIcon: true,
    blockColor: '#506CD2',
    blockWidth: 5,
    usePortalStyle: true,
    showMore: true,
    moreType: 'sys',
    moreUrl: '/workFlow/flowTodo',
    moreParams: {},
    showFresh: true,
    radius: 8,
    themeColor: '',
    titleBorder: '1px solid #EBEEF5',
    titleCss: '',
    opacity: 1,
    draggable: true,
    resizable: true,
    editable: true,
    lock: false,
    w: 12,
    h: 4,
    minW: 1,
    minH: 1,
    maxW: 24,
    maxH: 12,
    list: [
      { fullName: "功能设计", id: "85cd7bca426e49ce83a061bf461b1447", urlAddress: "onlineDev/webDesign", icon: "icon-ym icon-ym-webDesign", iconBackgroundColor: "#FF3B3B", type: 2 },
      { fullName: "流程设计", id: "fe0150960dd542ec9328067e4495074b", urlAddress: "workFlow/flowEngine", icon: "icon-ym icon-ym-flowDesign", iconBackgroundColor: "#7B1AE1", type: 2 },
      { fullName: "权限管理", id: "9057d797550e4457b7ddf2456ce45882", urlAddress: "permission/authorize", icon: "icon-ym icon-ym-authorize", iconBackgroundColor: "#1890FF", type: 2 },
      { fullName: "报表设计", id: "c7159f97177b420d9fc8ec8c74ae541b", urlAddress: "onlineDev/dataReport", icon: "icon-ym icon-ym-reportDesign", iconBackgroundColor: "#F68900", type: 2 },
      { fullName: "门户设计", id: "232d7226f00446d882e1e1bd999f7b2d", urlAddress: "onlineDev/visualPortal", icon: "icon-ym icon-ym-portalDesign", iconBackgroundColor: "#33B932", type: 2 }
    ],
  },
  {
    icon: 'icon-ym icon-ym-generator-Panel',
    label: '数据面板',
    ccitKey: 'dataBoard',
    title: '数据面板',
    showTitle: true,
    showBlock: true,
    showIcon: true,
    blockColor: '#506CD2',
    blockWidth: 5,
    usePortalStyle: true,
    showMore: true,
    moreType: 'sys',
    moreUrl: '/workFlow/flowTodo',
    moreParams: {},
    showFresh: true,
    radius: 8,
    themeColor: '',
    titleBorder: '1px solid #EBEEF5',
    titleCss: '',
    opacity: 1,
    draggable: true,
    resizable: true,
    editable: true,
    lock: false,
    w: 12,
    h: 4,
    minW: 1,
    minH: 1,
    maxW: 12,
    maxH: 6,
    list: [
      { fullName: "新增客户（个）", num: 262, dataType: 'static', dataInterface: '', icon: "icon-ym icon-ym-wf-contractApproval" },
      { fullName: "新增商机（个）", num: 199, dataType: 'static', dataInterface: '', icon: "icon-ym icon-ym-wf-outgoingApply" },
      { fullName: "合同金额（元）", num: 126263.5, dataType: 'static', dataInterface: '', icon: "icon-ym icon-ym-wf-payDistribution" },
      { fullName: "回款金额（元）", num: 6223.2, dataType: 'static', dataInterface: '', icon: "icon-ym icon-ym-wf-incomeRecognition" }
    ],
    dataInterface: '',
  },
  {
    icon: 'icon-ym icon-ym-generator-notice',
    label: '公告通知',
    ccitKey: 'notice',
    title: '公告通知',
    showTitle: true,
    showBlock: true,
    showIcon: true,
    blockColor: '#506CD2',
    blockWidth: 5,
    usePortalStyle: true,
    showMore: true,
    moreType: 'sys',
    moreUrl: '/workFlow/flowTodo',
    moreParams: {},
    showFresh: true,
    radius: 8,
    themeColor: '',
    titleBorder: '1px solid #EBEEF5',
    titleCss: '',
    opacity: 1,
    draggable: true,
    resizable: true,
    editable: true,
    lock: false,
    w: 8,
    h: 7,
    minW: 1,
    minH: 1,
    maxW: 24,
    maxH: 12,
  },
  {
    icon: 'el-icon-news',
    label: 'iframe元素',
    ccitKey: 'iframeDiv',
    title: 'iframe元素',
    showMore: true,
    moreType: 'sys',
    moreUrl: '',
    moreParams: {},
    showFresh: true,
    iframeUrl: '',
    param: '',
    radius: 8,
    showTitle: true,
    showBlock: true,
    showIcon: true,
    blockColor: '#506CD2',
    blockWidth: 5,
    usePortalStyle: true,
    themeColor: '',
    titleBorder: '1px solid #EBEEF5',
    titleCss: '',
    opacity: 1,
    events: [],
    w: 24,
    h: 6,
    minW: 1,
    minH: 1,
    maxW: 24,
    maxH: 12,
    draggable: true,
    resizable: true,
    editable: true,
    lock: false
  },
  {
    icon: 'ym-custom ym-custom-numeric--box-multiple-outline',
    label: '图片轮播',
    ccitKey: 'carousel',
    title: '图片轮播',
    showMore: true,
    moreType: 'sys',
    moreUrl: '',
    moreParams: {},
    showFresh: true,
    list: [],
    config: { interval: 3000, type: 'card', arrow: 'always', indicatorPosition: 'none', autoplay: 'false' },
    radius: 8,
    showTitle: true,
    showBlock: true,
    showIcon: true,
    blockColor: '#506CD2',
    blockWidth: 5,
    usePortalStyle: true,
    themeColor: '',
    titleBorder: '1px solid #EBEEF5',
    titleCss: '',
    opacity: 1,
    w: 24,
    h: 5,
    minW: 1,
    minH: 1,
    maxW: 24,
    maxH: 12,
    draggable: true,
    resizable: true,
    editable: true,
    lock: false
  },
  {
    icon: 'ym-custom ym-custom-email-outline',
    label: '我的邮箱',
    ccitKey: 'mailbox',
    title: '我的邮箱',
    showMore: true,
    moreType: 'sys',
    moreUrl: '',
    moreParams: {},
    showFresh: true,
    themeColor: '',
    titleBorder: '1px solid #EBEEF5',
    titleCss: '',
    opacity: 1,
    showTitle: true,
    showBlock: true,
    showIcon: true,
    blockColor: '#506CD2',
    blockWidth: 5,
    usePortalStyle: true,
    list: [
      { name: '写信', icon: 'icon-ym icon-ym-extend-pencil', type: 'write' },
      { name: '通讯录', icon: 'icon-ym icon-ym-generator-jobs', type: 'loadIn' },
      { name: '进入邮箱', icon: 'el-icon-right', type: 'loadIn' },
    ],
    radius: 8,
    w: 16,
    h: 6,
    minW: 1,
    minH: 1,
    maxW: 24,
    maxH: 12,
    draggable: true,
    resizable: true,
    editable: true,
    lock: false
  },
  {
    icon: 'ym-custom ym-custom-power',
    label: '单点登录',
    ccitKey: 'singleLogin',
    title: '单点登录',
    showMore: true,
    moreType: 'sys',
    moreUrl: '',
    moreParams: {},
    showFresh: true,
    themeColor: '',
    titleBorder: '1px solid #EBEEF5',
    titleCss: '',
    opacity: 1,
    showTitle: true,
    showBlock: true,
    showIcon: true,
    blockColor: '#506CD2',
    blockWidth: 5,
    usePortalStyle: true,
    list: [
      {
        name: "ERP系统",
        imgUrl: require('@/assets/images/singleLogin/erp.png'),
        sysUrl: "http://ame.chinacoalit.com/"
      },
      {
        name: "业财一体化",
        imgUrl: require('@/assets/images/singleLogin/money.png'),
        sysUrl: "http://ame.chinacoalit.com/"
      },
      {
        name: "OA系统",
        imgUrl: require('@/assets/images/singleLogin/oa.png'),
        sysUrl: "http://ame.chinacoalit.com/"
      },
      {
        name: "法律事务",
        imgUrl: require('@/assets/images/singleLogin/law.png'),
        sysUrl: "http://ame.chinacoalit.com/"
      },
      {
        name: "历史公文查询",
        imgUrl: require('@/assets/images/singleLogin/doc.png'),
        sysUrl: "http://ame.chinacoalit.com/"
      },
      {
        name: "应用运维",
        imgUrl: require('@/assets/images/singleLogin/manage.png'),
        sysUrl: "http://ame.chinacoalit.com/"
      },
      {
        name: "综合管理系统",
        imgUrl: require('@/assets/images/singleLogin/manage.png'),
        sysUrl: "http://ame.chinacoalit.com/"
      },
      {
        name: "阿米加",
        imgUrl: require('@/assets/images/singleLogin/ame.png'),
        sysUrl: "http://ame.chinacoalit.com/"
      },
      {
        name: "业务综合管理",
        imgUrl: require('@/assets/images/singleLogin/business.png'),
        sysUrl: "http://ame.chinacoalit.com/"
      },
      {
        name: "易购",
        imgUrl: require('@/assets/images/singleLogin/shop.png'),
        sysUrl: "http://ame.chinacoalit.com/"
      },
    ],
    radius: 8,
    events: [],
    w: 8,
    h: 5,
    minW: 1,
    minH: 1,
    maxW: 24,
    maxH: 12,
    draggable: true,
    resizable: true,
    editable: true,
    lock: false
  },
  {
    icon: 'ym-custom ym-custom-calendar-check',
    label: '我的事项',
    ccitKey: 'dailySchedule',
    title: '我的事项',
    showMore: true,
    moreType: 'sys',
    moreUrl: '',
    moreParams: {},
    showFresh: true,
    themeColor: '',
    titleBorder: '1px solid #EBEEF5',
    titleCss: '',
    opacity: 1,
    showBtn: false,
    reverse: false,
    radius: 8,
    showTitle: true,
    showBlock: true,
    showIcon: true,
    blockColor: '#506CD2',
    blockWidth: 5,
    usePortalStyle: true,
    isCollapes: true,
    scheduleType: 'timeline',
    showAdd: true,
    showWeather: true,
    w: 6,
    h: 16,
    minW: 1,
    minH: 1,
    maxW: 24,
    maxH: 24,
    draggable: true,
    resizable: true,
    editable: true,
    lock: false
  },
  {
    icon: 'ym-custom ym-custom-weather-cloudy',
    label: '天气预报',
    ccitKey: 'weather',
    title: '天气预报',
    showMore: true,
    moreType: 'sys',
    moreUrl: '',
    moreParams: {},
    showFresh: true,
    showTitle: true,
    showBlock: true,
    showIcon: true,
    blockColor: '#506CD2',
    blockWidth: 5,
    usePortalStyle: true,
    mode: 'standard',
    themeColor: '',
    titleBorder: '1px solid #EBEEF5',
    titleCss: '',
    opacity: 1,
    radius: 8,
    themeColor: '#fff',
    w: 12,
    h: 4,
    minW: 1,
    minH: 1,
    maxW: 24,
    maxH: 12,
    draggable: true,
    resizable: true,
    editable: true,
    lock: false
  },
  {
    icon: 'ym-custom ym-custom-cellphone-link',
    label: '通讯录',
    ccitKey: 'contactBook',
    title: '通讯录',
    showMore: true,
    moreType: 'sys',
    moreUrl: '',
    moreParams: {},
    showFresh: true,
    showTitle: true,
    showBlock: true,
    showIcon: true,
    blockColor: '#506CD2',
    blockWidth: 5,
    usePortalStyle: true,
    showHeader: true,
    themeColor: '',
    titleBorder: '1px solid #EBEEF5',
    titleCss: '',
    opacity: 1,
    radius: 8,
    showPagination: true,
    list: [
      { label: '账号', prop: 'account', selection: true },
      { label: '姓名', prop: 'realName', selection: true },
      { label: '性别', prop: 'gender', selection: true },
      { label: '手机', prop: 'mobilePhone', selection: true },
      { label: '部门', prop: 'department', selection: true },
      { label: '岗位', prop: 'position', selection: true },
    ],
    w: 16,
    h: 6,
    minW: 1,
    minH: 1,
    maxW: 24,
    maxH: 12,
    draggable: true,
    resizable: true,
    editable: true,
    lock: false
  },
  {
    icon: 'icon-ym icon-ym-file-photo',
    label: '图片元素',
    ccitKey: 'singlePicture',
    title: '图片元素',
    showMore: true,
    moreType: 'sys',
    moreUrl: '',
    moreParams: {},
    showFresh: true,
    showTitle: true,
    showBlock: true,
    showIcon: true,
    blockColor: '#506CD2',
    blockWidth: 5,
    usePortalStyle: true,
    themeColor: '',
    titleBorder: '1px solid #EBEEF5',
    titleCss: '',
    opacity: 1,
    radius: 8,
    fileId: '',
    fit: 'fill',
    w: 6,
    h: 4,
    minW: 1,
    minH: 1,
    maxW: 24,
    maxH: 12,
    draggable: true,
    resizable: true,
    editable: true,
    lock: false
  },
  {
    icon: 'el-icon-s-data',
    label: '建模查询中心',
    ccitKey: 'modelQuery',
    title: '建模查询中心',
    dataInterface: '',
    showMore: true,
    moreType: 'sys',
    moreUrl: '',
    moreParams: {},
    showFresh: true,
    themeColor: '',
    titleBorder: '1px solid #EBEEF5',
    titleCss: '',
    opacity: 1,
    radius: 8,
    showTitle: true,
    showBlock: true,
    showIcon: true,
    blockColor: '#506CD2',
    blockWidth: 5,
    usePortalStyle: true,
    showHeader: true,
    showBorder: false,
    showStripe: true,
    columns: [{
      prop: 'name',
      label: '项目名称',
      width: 120,
      selection: true
    }, {
      prop: 'type',
      label: '项目类型',
      width: 120,
      selection: true
    },
    {
      prop: 'enCode',
      label: '项目编码',
      width: 150,
      selection: true
    },
    {
      prop: 'chargeUser',
      label: '负责人',
      selection: true
    },
    {
      prop: 'startTime',
      label: '开始时间',
      selection: true
    }
    ],
    data: [
      {
        name: '装修报价预估',
        type: '房产',
        enCode: 'HJG_NJ678',
        chargeUser: 'admin',
        startTime: '2022-01-01'
      },
      {
        name: '无人机技术研发',
        type: '计算机',
        enCode: 'WRJ_YF123',
        chargeUser: 'admin',
        startTime: '2022-04-18'
      },
      {
        name: '装修报价预估',
        type: '房产',
        enCode: 'HJG_NJ678',
        chargeUser: 'admin',
        startTime: '2022-01-01'
      },
      {
        name: '无人机技术研发',
        type: '计算机',
        enCode: 'WRJ_YF123',
        chargeUser: 'admin',
        startTime: '2022-04-18'
      },
      {
        name: '装修报价预估',
        type: '房产',
        enCode: 'HJG_NJ678',
        chargeUser: 'admin',
        startTime: '2022-01-01'
      },
      {
        name: '无人机技术研发',
        type: '计算机',
        enCode: 'WRJ_YF123',
        chargeUser: 'admin',
        startTime: '2022-04-18'
      }
    ],
    w: 8,
    h: 8,
    minW: 1,
    minH: 1,
    maxW: 24,
    maxH: 15,
    draggable: true,
    resizable: true,
    editable: true,
    lock: false
  },
  {
    icon: 'ym-custom ym-custom-sort-descending',
    label: '排行榜',
    ccitKey: 'rankList',
    title: '排行榜',
    dataInterface: '',
    showMore: true,
    moreType: 'sys',
    moreUrl: '',
    moreParams: {},
    showFresh: true,
    themeColor: '',
    titleBorder: '1px solid #EBEEF5',
    titleCss: '',
    opacity: 1,
    listSize: 5,
    sortField: 'value',
    sortType: 'desc',
    displayType: 'list',
    axisField: '',
    dynamic: true,
    interval: 10,
    showHeader: true,
    radius: 8,
    showTitle: true,
    showBlock: true,
    showIcon: true,
    blockColor: '#506CD2',
    blockWidth: 5,
    usePortalStyle: true,
    columns: [
      {
        label: "对象",
        prop: "name",
        span: 8,
      },
      {
        label: "数据",
        prop: "value",
        span: 8,
      },
    ],
    list: [
      {
        name: '何梦松',
        value: 123
      },
      {
        name: '孟怜梦',
        value: 222
      },
      {
        name: '封梦之',
        value: 345
      },
      {
        name: '查书瑶',
        value: 782
      },
    ],
    w: 12,
    h: 8,
    minW: 1,
    minH: 1,
    maxW: 24,
    maxH: 12,
    draggable: true,
    resizable: true,
    editable: true,
    lock: false
  },
  {
    icon: 'el-icon-video-camera',
    label: '视频元素',
    ccitKey: 'CCITVideo',
    title: "视频元素",
    showMore: true,
    moreType: 'sys',
    moreUrl: '',
    moreParams: {},
    showFresh: true,
    radius: 8,
    usePortalStyle: true,
    showTitle: false,
    themeColor: '',
    titleBorder: '1px solid #EBEEF5',
    titleCss: '',
    opacity: 1,
    config: { autoplay: false, loop: false },
    fileId: '',
    w: 5,
    h: 5,
    minW: 4,
    minH: 4,
    maxW: 8,
    maxH: 8,
    draggable: true,
    resizable: true,
    editable: true,
    lock: false
  },
  {
    icon: 'el-icon-map-location',
    label: '地图元素',
    ccitKey: 'CCITMap',
    title: '地图元素',
    showMore: true,
    moreType: 'sys',
    moreUrl: '',
    moreParams: {},
    showFresh: true,
    radius: 8,
    showTitle: true,
    showBlock: true,
    showIcon: true,
    blockColor: '#506CD2',
    blockWidth: 5,
    usePortalStyle: true,
    themeColor: '',
    titleBorder: '1px solid #EBEEF5',
    titleCss: '',
    opacity: 1,
    point: {
      lng: 0, //经度
      lat: 0 //纬度
    },
    zoom: 17, //缩放级别
    address: '',
    searchable: true,
    w: 4,
    h: 4,
    minW: 6,
    minH: 6,
    maxW: 24,
    maxH: 12,
    draggable: true,
    resizable: true,
    editable: true,
    lock: false
  },
  {
    icon: 'icon-ym icon-ym-wf-staffOvertime',
    label: '时间线',
    ccitKey: 'timeLine',
    title: '时间线',
    dataInterface: '',
    showMore: true,
    moreType: 'sys',
    moreUrl: '',
    moreParams: {},
    showFresh: true,
    radius: 8,
    showTitle: true,
    showBlock: true,
    showIcon: true,
    blockColor: '#506CD2',
    blockWidth: 5,
    usePortalStyle: true,
    themeColor: '',
    titleBorder: '1px solid #EBEEF5',
    titleCss: '',
    opacity: 1,
    reverse: false,
    format: 'yyyy-MM-dd',
    list: [
      {
        content: "创建成功",
        timestamp: "2022-04-11",
        status: 0,
        color: '',
        icon: '',
      },
      {
        content: "通过审核",
        timestamp: "2022-04-13",
        status: 0,
        color: '',
        icon: '',
      },
      {
        content: "活动按期开始",
        timestamp: "2022-04-15",
        status: 1,
        color: '',
        icon: '',
      },
      {
        content: "活动结束",
        timestamp: "2022-04-18",
        status: 2,
        color: '',
        icon: '',
      },
    ],
    node: {
      noStart: {
        color: '#e4e7ed',
        icon: 'el-icon-finished',
        condition: -1,
        value: 1
      },
      progress: {
        color: '#0bbd87',
        icon: 'el-icon-loading',
        condition: 0,
        value: 1
      },
      finish: {
        color: '#409eff',
        icon: 'el-icon-check',
        condition: 1,
        value: 1
      }
    },
    statusField: 'status',
    w: 4,
    h: 6,
    minW: 2,
    minH: 2,
    maxW: 8,
    maxH: 10,
    draggable: true,
    resizable: true,
    editable: true,
    lock: false
  },
  {
    icon: 'icon-ym icon-ym-generator-time',
    label: '当前时间',
    ccitKey: 'currentTime',
    title: '当前时间',
    showMore: true,
    moreType: 'sys',
    moreUrl: '',
    moreParams: {},
    showFresh: true,
    radius: 8,
    showTitle: true,
    showBlock: true,
    showIcon: true,
    blockColor: '#506CD2',
    blockWidth: 5,
    usePortalStyle: true,
    themeColor: '',
    titleBorder: '1px solid #EBEEF5',
    titleCss: '',
    opacity: 1,
    format: 'YYYY年MM月DD日 HH:mm:ss',
    color: '#3A8AD1',
    fontSize: 18,
    fontFamily: 'PingFang SC',
    showWeek: true,
    showClock: true,
    css: '',
    w: 12,
    h: 6,
    minW: 2,
    minH: 1,
    maxW: 18,
    maxH: 12,
    draggable: true,
    resizable: true,
    editable: true,
    lock: false
  },
  // {
  //   icon: 'ym-custom ym-custom-newspaper',
  //   label: '企业新闻',
  //   ccitKey: 'news',
  //   title: '企业新闻',
  //   showMore: true,
  //   moreType: 'sys',
  //   moreUrl: '',
  //   showTitle: true,
  //   showBlock: true,
  //   showIcon: true,
  //   blockColor: '#506CD2',
  //   blockWidth: 5,
  //   usePortalStyle: true,
  //   themeColor: '', titleBorder: '1px solid #EBEEF5',
  //   radius: 8,
  //   categoryCode: '',
  //   columns: [{
  //     label: '标题', prop: 'title',
  //     selection: true,
  //   },
  //   {
  //     label: '所属栏目', prop: 'categoryName',
  //     selection: false,
  //   },
  //   {
  //     label: '创建人', prop: 'createBy',
  //     selection: false,
  //   },
  //   {
  //     label: '创建时间', prop: 'createDate',
  //     selection: true,
  //     width: 120
  //   }],
  //   showHeader: false,
  //   showCarousel: true,
  //   showRecommend: true,
  //   w: 12,
  //   h: 7,
  //   minW: 3,
  //   minH: 7,
  //   maxW: 24,
  //   maxH: 16,
  //   draggable: true,
  //   resizable: true,
  //   editable: true,
  //   lock: false
  // },
]
// 图表控件 【左面板】
export const chartComponents = [{
  icon: 'icon-ym icon-ym-generator-bar',
  label: '柱状图',
  ccitKey: 'barChart',
  title: '柱状图',
  dataInterface: '',
  showMore: true,
  moreType: 'sys',
  moreUrl: '',
  moreParams: {},
  showFresh: true,
  themeColor: '',
  titleBorder: '1px solid #EBEEF5',
  titleCss: '',
  opacity: 1,
  radius: 8,
  showTitle: true,
  showBlock: true,
  showIcon: true,
  blockColor: '#506CD2',
  blockWidth: 5,
  usePortalStyle: true,
  markLine: [],
  markPoint: [],
  //配置
  props: {
    barWidth: 30,
    groupColorList: [],
    directionValue: '纵向',
    alignWithLabel: true,
    splitLineShow: false,
    stack: false,
    showValue: false,
    valuePosition: ''
  },
  option: {
    color: [],
    title: {
      text: '',
      subtext: '',
    },
    legend: {
      show: true,
      data: []
    },
    toolbox: {
      feature: {
        dataView: { show: false, readOnly: true },
        magicType: { show: false, type: ['line', 'bar'] },
        saveAsImage: { show: false }
      }
    },
    tooltip: {
      trigger: 'axis',
      axisPointer: { type: 'shadow' }
    },
    grid: {
      left: '3%',
      right: '15%', //避免纵坐标值显示不全，所以调大一点
      bottom: '3%',
      containLabel: true
    },
    xAxis: [{
      name: '',
      type: 'category',
      data: ['1月', '2月', '3月', '4月', '5月', '6月'],
      axisTick: { alignWithLabel: true },
      splitLine: { show: false }
    }],
    yAxis: [{
      name: '',
      type: 'value',
    }],
    series: [{
      name: '销售量',
      type: 'bar',
      barWidth: '60%',
      data: [1012, 500, 800, 868, 653, 372]
    }],
  },
  w: 6,
  h: 8,
  minW: 4,
  minH: 8,
  maxW: 12,
  maxH: 20,
  draggable: true,
  resizable: true,
  editable: true,
  lock: false
},
{
  icon: 'icon-ym icon-ym-generator-pie',
  label: '饼图',
  ccitKey: 'pieChart',
  title: '饼图',
  showMore: true,
  moreType: 'sys',
  moreUrl: '',
  moreParams: {},
  showFresh: true,
  themeColor: '',
  titleBorder: '1px solid #EBEEF5',
  titleCss: '',
  opacity: 1,
  radius: 8,
  showTitle: true,
  showBlock: true,
  showIcon: true,
  blockColor: '#506CD2',
  blockWidth: 5,
  usePortalStyle: true,
  //配置
  props: {
    groupColorList: [],
  },
  option: {
    title: {
      subtext: '',
      left: 'center'
    },
    tooltip: {
      trigger: 'item',
      formatter: '{a} <br/>{b} : {c} ({d}%)'
    },
    legend: {
      // orient: 'vertical',
      // top: 'middle',
      bottom: 10,
      left: 'center',
      data: ['西凉', '益州', '兖州', '荆州', '幽州']
    },
    series: [{
      type: 'pie',
      radius: '65%',
      center: ['50%', '50%'],
      selectedMode: 'single',
      data: [{ value: 1548, name: '幽州', itemStyle: { color: '#1890ff' } },
        { value: 535, name: '荆州', itemStyle: { color: '#ff3b3b' } },
        { value: 510, name: '兖州', itemStyle: { color: '#7b1ae1' } },
        { value: 634, name: '益州', itemStyle: { color: '#f68900' } },
        { value: 735, name: '西凉', itemStyle: { color: '#33b932' } }
      ],
      emphasis: {
        itemStyle: {
          shadowBlur: 10,
          shadowOffsetX: 0,
          shadowColor: 'rgba(0, 0, 0, 0.5)'
        }
      }
    }],
    toolbox: {
      feature: {
        dataView: { show: false, readOnly: true },
        saveAsImage: { show: false }
      }
    },
  },
  w: 6,
  h: 8,
  minW: 4,
  minH: 8,
  maxW: 12,
  maxH: 20,
  draggable: true,
  resizable: true,
  editable: true,
  lock: false
},
{
  icon: 'icon-ym icon-ym-generator-line',
  label: '折线图',
  ccitKey: 'lineChart',
  title: '折线图',
  showMore: true,
  moreType: 'sys',
  moreUrl: '',
  moreParams: {},
  showFresh: true,
  themeColor: '',
  titleBorder: '1px solid #EBEEF5',
  titleCss: '',
  opacity: 1,
  radius: 8,
  showTitle: true,
  showBlock: true,
  showIcon: true,
  blockColor: '#506CD2',
  blockWidth: 5,
  usePortalStyle: true,
  //配置
  props: {
    groupColorList: [],
    directionValue: '纵向',
    alignWithLabel: true,
    splitLineShow: false,
    stack: false,
    showValue: false,
    valuePosition: ''
  },
  option: {
    theme: '',
    title: {
      text: ''
    },
    tooltip: {
      trigger: 'axis'
    },
    grid: {
      left: '3%',
      right: '10%',
      top: '3%',
      bottom: '3%',
      containLabel: true
    },
    toolbox: {
      feature: {
        saveAsImage: {}
      }
    },
    legend: {
      data: ['邮件营销', '联盟广告', '视频广告', '直接访问', '搜索引擎']
    },
    xAxis: {
      type: 'category',
      boundaryGap: false,
      data: ['周一', '周二', '周三', '周四', '周五', '周六', '周日'],
      axisTick: { alignWithLabel: false },
      splitLine: { show: false }
    },
    yAxis: {
      type: 'value'
    },
    series: [{
        name: '邮件营销',
        type: 'line',
        stack: '总量',
        data: [120, 132, 101, 134, 90, 230, 210],
        itemStyle: { color: '#33b932' }
      },
      {
        name: '联盟广告',
        type: 'line',
        stack: '总量',
        data: [220, 182, 191, 234, 290, 330, 310],
        itemStyle: { color: '#ff3b3b' }
      },
      {
        name: '视频广告',
        type: 'line',
        stack: '总量',
        data: [150, 232, 201, 154, 190, 330, 410],
        itemStyle: { color: '#7b1ae1' }
      },
      {
        name: '直接访问',
        type: 'line',
        stack: '总量',
        data: [320, 332, 301, 334, 390, 330, 320],
        itemStyle: { color: '#1890ff' }
      },
      {
        name: '搜索引擎',
        type: 'line',
        stack: '总量',
        data: [820, 932, 901, 934, 1290, 1330, 1320],
        itemStyle: { color: '#f68900' }
      }
    ]
  },
  w: 6,
  h: 8,
  minW: 4,
  minH: 8,
  maxW: 12,
  maxH: 20,
  draggable: true,
  resizable: true,
  editable: true,
  lock: false
},
{
  icon: 'icon-ym icon-ym-generator-annular',
  label: '环形图',
  ccitKey: 'annularChart',
  title: '环形图',
  showMore: true,
  moreType: 'sys',
  moreUrl: '',
  moreParams: {},
  showFresh: true,
  themeColor: '',
  titleBorder: '1px solid #EBEEF5',
  titleCss: '',
  opacity: 1,
  radius: 8,
  showTitle: true,
  showBlock: true,
  showIcon: true,
  blockColor: '#506CD2',
  blockWidth: 5,
  usePortalStyle: true,
  //配置
  props: {
    groupColorList: [],
  },
  option: {
    theme: '',
    tooltip: {
      trigger: 'item',
      formatter: '{a} <br/>{b}: {c} ({d}%)'
    },
    legend: {
      orient: 'vertical',
      left: 10,
      data: ['直接访问', '邮件营销', '联盟广告', '视频广告', '搜索引擎']
    },
    series: [{
      name: '访问来源',
      type: 'pie',
      radius: ['50%', '70%'],
      avoidLabelOverlap: false,
      label: {
        show: false,
        position: 'center'
      },
      emphasis: {
        label: {
          show: true,
          fontSize: '30',
          fontWeight: 'bold'
        }
      },
      labelLine: {
        show: false
      },
      data: [
        { value: 335, name: '直接访问', itemStyle: { color: '#33b932' } },
        { value: 310, name: '邮件营销', itemStyle: { color: '#ff3b3b' } },
        { value: 234, name: '联盟广告', itemStyle: { color: '#7b1ae1' } },
        { value: 135, name: '视频广告', itemStyle: { color: '#f68900' } },
        { value: 1548, name: '搜索引擎', itemStyle: { color: '#1890ff' } }
      ]
    }]
  },
  w: 6,
  h: 8,
  minW: 4,
  minH: 8,
  maxW: 12,
  maxH: 20,
  draggable: true,
  resizable: true,
  editable: true,
  lock: false
},
{
  icon: 'icon-ym icon-ym-generator-area',
  label: '面积图',
  ccitKey: 'areaChart',
  title: '面积图',
  showMore: true,
  moreType: 'sys',
  moreUrl: '',
  moreParams: {},
  showFresh: true,
  themeColor: '',
  titleBorder: '1px solid #EBEEF5',
  titleCss: '',
  opacity: 1,
  radius: 8,
  showTitle: true,
  showBlock: true,
  showIcon: true,
  blockColor: '#506CD2',
  blockWidth: 5,
  usePortalStyle: true,
  //配置
  props: {
    groupColorList: [],
  },
  option: {
    xAxis: {
      type: 'category',
      boundaryGap: false,
      data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
    },
    yAxis: {
      type: 'value'
    },
    series: [{
      data: [820, 932, 901, 934, 1290, 1330, 1320],
      type: 'line',
      areaStyle: {
        color: '#d0e2f3'
      },
      itemStyle: {
        normal: {
          color: '#1890FF',
          lineStyle: { color: '#1890FF' }
        }
      },
    }]
  },
  w: 6,
  h: 8,
  minW: 4,
  minH: 8,
  maxW: 12,
  maxH: 20,
  draggable: true,
  resizable: true,
  editable: true,
  lock: false
},
{
  icon: 'icon-ym icon-ym-generator-radar',
  label: '雷达图',
  ccitKey: 'radarChart',
  title: '雷达图',
  showMore: true,
  moreType: 'sys',
  moreUrl: '',
  moreParams: {},
  showFresh: true,
  themeColor: '',
  titleBorder: '1px solid #EBEEF5',
  titleCss: '',
  opacity: 1,
  radius: 8,
  showTitle: true,
  showBlock: true,
  showIcon: true,
  blockColor: '#506CD2',
  blockWidth: 5,
  usePortalStyle: true,
  //配置
  props: {
    groupColorList: [],
  },
  option: {
    title: {
      text: '雷达图'
    },
    grid: {
      left: '3%',
      right: '10%',
      top: '3%',
      bottom: '3%'
    },
    tooltip: {},
    legend: {
      data: ['预算分配（Allocated Budget）', '实际开销（Actual Spending）']
    },
    radar: {
      shape: 'circle',
      name: {
        textStyle: {
          color: '#fff',
          backgroundColor: '#999',
          borderRadius: 3,
          padding: [3, 5]
        }
      },
      indicator: [
        { name: '销售（sales）', max: 6500 },
        { name: '管理（Administration）', max: 16000 },
        { name: '信息技术（Information Techology）', max: 30000 },
        { name: '客服（Customer Support）', max: 38000 },
        { name: '研发（Development）', max: 52000 },
        { name: '市场（Marketing）', max: 25000 }
      ]
    },
    series: [{
      name: '预算 vs 开销（Budget vs spending）',
      type: 'radar',
      // areaStyle: {normal: {}},
      data: [{
        value: [4300, 10000, 28000, 35000, 50000, 19000],
        name: '预算分配（Allocated Budget）',
        itemStyle: { color: '#ff3b3b' }
      },
      {
        value: [5000, 14000, 28000, 31000, 42000, 21000],
        name: '实际开销（Actual Spending）',
        itemStyle: { color: '#1890ff' }
      }
      ]
    }]
  },
  w: 6,
  h: 8,
  minW: 4,
  minH: 8,
  maxW: 12,
  maxH: 20,
  draggable: true,
  resizable: true,
  editable: true,
  lock: false
}
]
